spring.application.name=Portfolio
spring.config.import=optional:file:portfolio/.env[.properties]
server.port=${PORT:8080}
server.address=0.0.0.0

github.username=${GITHUB_USERNAME:kimoiboi}
github.token=${GITHUB_TOKEN:}

portfolio.admin.username=${PORTFOLIO_ADMIN_USERNAME:kimoiboi}
portfolio.admin.password-bcrypt=${PORTFOLIO_ADMIN_PASSWORD_BCRYPT:}
portfolio.admin.totp-secret=${PORTFOLIO_ADMIN_TOTP_SECRET}