spring.application.name=Portfolio
server.port=${PORT:8080}
server.address=0.0.0.0

github.username=${GITHUB_USERNAME:kimoiboi}
github.token=${GITHUB_TOKEN:}

portfolio.admin.username=${PORTFOLIO_ADMIN_USERNAME:kimoiboi}
portfolio.admin.password-bcrypt=${PORTFOLIO_ADMIN_PASSWORD_BCRYPT:}